ALTER TABLE "AppSettings" ADD COLUMN IF NOT EXISTS "voiceTemplates" JSONB NOT NULL DEFAULT '[]';
ALTER TABLE "AppSettings" ADD COLUMN IF NOT EXISTS "notifications" JSONB;
ALTER TABLE "AppSettings" ADD COLUMN IF NOT EXISTS "branding" JSONB;
