ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "contact" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "phone" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "briefContent" JSONB;
