ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "email" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "website" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "commissionType" TEXT NOT NULL DEFAULT 'percent';
ALTER TABLE "Business" ADD COLUMN IF NOT EXISTS "commissionValue" TEXT NOT NULL DEFAULT '';
